CREATE DATABASE DOCUMENTACION
USE DOCUMENTACION
GO

DROP TABLE ROL
GO
DROP TABLE USUARIO
GO
DROP TABLE CLIENTE
GO
DROP TABLE EMPLEADOS
GO
DROP TABLE PROVEEDOR
GO
DROP TABLE CATEGORIA
GO

CREATE TABLE ROL
(
	ID_ROL NVARCHAR(90) PRIMARY KEY NOT NULL,
	NOMBRE_ROL NVARCHAR(90) NOT NULL,
	DESCRIPCION TEXT NOT NULL
)
GO

CREATE TABLE USUARIO
(
	ID_USUARIO NVARCHAR(90) PRIMARY KEY NOT NULL,
	ID_ROL NVARCHAR(90) NOT NULL FOREIGN KEY REFERENCES ROL(ID_ROL),		
	NOMBRE_USUARIO NVARCHAR(90) NOT NULL,
	PASSWORD_USUARIO NVARCHAR(90) NOT NULL,
	ESTADO_USUARIO NVARCHAR(90) NOT NULL
)
GO

CREATE TABLE CLIENTE
(
	ID_CLIENTE NVARCHAR(90) NOT NULL PRIMARY KEY,
	NOMBRE_CLIENTE	NVARCHAR(90) NOT NULL,
	APELLIDO_CLIENTE NVARCHAR(90) NOT NULL,
	DIRECCION_CLIENTE NVARCHAR(90) NOT NULL,
	NOMBRE_EMPRESA NVARCHAR(90) NOT NULL,
	NOMBRE_CONTACTO NVARCHAR(90) NOT NULL,
	PAIS_CLIENTE NVARCHAR(90) NOT NULL,
	MONEDA FLOAT NOT NULL,
	REGION_CLIENTE NVARCHAR(90) NOT NULL,
	CP_CLIENTE NVARCHAR(90) NOT NULL,
	TELEFONO_CLIENTE NVARCHAR(90) NOT NULL,
	FAX_CLIENTE	NVARCHAR(90) NOT NULL,
	EMAIL_CLIENTE NVARCHAR(90) NOT NULL,
	ID_USUARIO NVARCHAR(90) NOT NULL FOREIGN KEY REFERENCES USUARIO(ID_USUARIO),
	NUM_REGISTRO INT NOT NULL,
	DUI	NVARCHAR(90) NOT NULL,
	NIT	NVARCHAR(90) NOT NULL,
	DIAS_CREDITO FLOAT NOT NULL,
	LIMITE_CREDITO FLOAT NOT NULL
)
GO

CREATE TABLE EMPLEADOS
(
	ID_EMPLEADO NVARCHAR(90) PRIMARY KEY NOT NULL,
	COD_EMPLEADO INT NOT NULL,
	NOMBRE_EMPLEADO NVARCHAR(90) NOT NULL,
	APELLIDO_EMPLEADO NVARCHAR(90) NOT NULL,
	DPTO_EMPLEADO NVARCHAR(90) NOT NULL,
	FECHA_INGRESO DATE NOT NULL,
	TELEFONO_EMPLEADO NVARCHAR(90) NOT NULL,
	EMAIL_EMPLEADO BINARY NOT NULL,
	ID_USUARIO NVARCHAR(90) NOT NULL FOREIGN KEY REFERENCES USUARIO(ID_USUARIO),
	FECHA_NACIMIENTO DATE NOT NULL,
	ESTUDIOS_ACADEMICOS TEXT NOT NULL
)
GO

CREATE TABLE PROVEEDOR
(
	ID_PROVEEDOR NVARCHAR(90) PRIMARY KEY NOT NULL,
	NOMBRE_EMPRESA NVARCHAR(90) NOT NULL,
	NOMBRE_CONTACTO NVARCHAR(90) NOT NULL,
	DIRECCION_PROV NVARCHAR(90) NOT NULL,
	CIUDAD_PROV NVARCHAR(90) NOT NULL,
	REGION_PROV NVARCHAR(90) NOT NULL,
	CP_PROV INT NOT NULL,
	PAIS_PROV NVARCHAR(90) NOT NULL,
	TELEFONO_PROV NVARCHAR(90) NOT NULL,
	FAX_PROV NVARCHAR(90) NOT NULL,
	EMAIL_PROV NVARCHAR(90) NOT NULL,
	WEB_PROV BINARY NOT NULL
)
GO

CREATE TABLE CATEGORIA
(
	ID_CATEGORIA NVARCHAR(90) PRIMARY KEY NOT NULL,
	NOMBRE_CATEGORIA NVARCHAR(90) NOT NULL,
	TIPO_REPUESTO NVARCHAR(90) NOT NULL,
	DESCRIPCION TEXT NOT NULL
)
GO

ALTER TABLE CATEGORIA ADD ID_PROVEEDOR NVARCHAR(90) NOT NULL FOREIGN KEY REFERENCES PROVEEDOR(ID_PROVEEDOR)
GO

ALTER TABLE PROVEEDOR ADD ID_USUARIO NVARCHAR(90) NOT NULL FOREIGN KEY REFERENCES USUARIO(ID_USUARIO)
GO